version: "3"
services:
  mysql:
    image: mysql:5.7
    container_name: project_mysql
    networks:
      default:
        ipv4_address: 192.168.56.3
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
      MYSQL_ROOT_PASSWORD:
      MYSQL_DATABASE: project
      MYSQL_USER: root
      MYSQL_PASSWORD:
    ports:
      - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: project_phpmyadmin
    links:
      - mysql
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    restart: always
    networks:
      default:
        ipv4_address: 192.168.56.4
    ports:
      - 8183:80

  web:
    build: ./php
    container_name: project_web
    networks:
      default:
        ipv4_address: 192.168.56.2
    volumes:
      - ./../src:/var/www/html/
      - ./php/virtualhost.conf:/etc/apache2/sites-available/000-default.conf
    ports:
      - "8080:8080"
      - "80:80"
    depends_on:
      - "mysql"

  develop_init:
    build: ./php
    container_name: project_develop_init
    volumes:
      - ./../src:/var/www/html/
    depends_on:
      - "mysql"
      - "web"

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.56.0/24